### ISSUE TITLE
can you help with an explanation?

### ISSUE THREAD

**Issue by ktakanopy** [S-Choudhuri/Adversarial-Domain-Adaptation-with-Keras#4]
https://github.com/S-Choudhuri/Adversarial-Domain-Adaptation-with-Keras/blob/7cfc5456e3380e60044287f70564f7c910da0737/driver.py#L97

Hello, could you explain how this line treats the gradient reversal without using negative forwards ? 

And what is the weight_class and weight_adv?

**Comment by S-Choudhuri** [comment]
Hi,

1) Instead of using gradient reversal layer to flip the gradients, I am doing GAN-style loss (I am reversing the labels) so it's not needed.

2) "weight_class" contains the weights for every sample in the batch (a degree of contribution in the classification loss), the first-half of the batch contains the source samples and therefore will participate in computing the classifier loss . Second-half consists of the target samples which should not participate in the classifier loss computation (since they do not have ground-truth labels), therefore assigned 0 weights.

3) Similar to "weight_class", "weight_adv" contains the weights for every sample in the batch (a degree of contribution in the discrimination loss).
